name: AWS OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::471112658477:role/GitHubActionsVolcanicRole
          aws-region: us-east-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Test allowed S3 read
        run: aws s3 cp s3://volcanic-data-platform-lab-xxxx-471112658477-us-east-2-an/bronze/sample.txt -

      - name: Test denied S3 write
        shell: bash
        run: |
          echo "This write should be denied" > denied-test.txt

          if aws s3 cp denied-test.txt s3://volcanic-data-platform-lab-xxxx-471112658477-us-east-2-an/bronze/denied-test.txt; then
            echo "ERROR: write unexpectedly succeeded"
            exit 1
          else
            echo "SUCCESS: write was denied as expected"
          fi